# Generated by Django 5.0.6 on 2024-07-03 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255)),
                ('image_name', models.CharField(max_length=255)),
                ('blog_image', models.ImageField(upload_to='blog/image/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
                ('update_date', models.DateField()),
                ('blog_cetagory', models.CharField(choices=[('Techonology', 'Technology'), ('Programming', 'Programming'), ('Economy', 'Economy'), ('Hacking', 'Hacking'), ('Politics', 'Politics'), ('Sports', 'Sports'), ('Esport', 'Esports'), ('Others', 'Others')], max_length=255)),
            ],
        ),
    ]
