# Generated by Django 5.0.6 on 2024-07-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='blog_paragraph',
            field=models.TextField(default=' '),
        ),
    ]
