# Generated by Django 5.0.6 on 2024-07-03 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('years', models.CharField(max_length=255)),
                ('semester', models.IntegerField(help_text='Invalid semester', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('faculty', models.CharField(max_length=255)),
            ],
        ),
    ]
