# Generated by Django 5.0.6 on 2024-07-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='file',
            new_name='file_path',
        ),
    ]
