# Generated by Django 5.0.6 on 2024-07-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfile', '0002_rename_file_uploadfile_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='file_path',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='faculty',
            field=models.CharField(choices=[('BIT', 'BIT'), ('BHM', 'BHM'), ('BBA', 'BBA'), ('MBA', 'MBA')], max_length=255),
        ),
    ]
