# Generated by Django 5.0.6 on 2024-07-04 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logo/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
            ],
        ),
    ]
